### Liabraries importing Toolkit


In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


### Data Understanding & Exploration

In [2]:

df = pd.read_csv(r'C:\Users\ketan sonawane\OneDrive\Desktop\VisionAI\ishihara_ml_dataset_10000_rows.csv')
df.head(10)

,control_fail,red_fail,green_fail,vanishing_seen,total_correct,total_seen,label
0,0,0,1,0,22,22,Normal
1,4,6,4,2,4,8,RG_Deficient
2,0,1,4,1,11,18,Deuteranopia
3,0,1,1,0,22,22,Normal
4,0,4,2,1,11,16,Protanopia
5,0,1,1,0,23,24,Normal
6,0,1,1,0,23,23,Normal
7,0,7,2,0,12,16,Protanopia
8,2,7,7,3,4,7,RG_Deficient
9,0,0,1,0,23,23,Normal


### Data understanding Toolkit


In [3]:
print(df.head())
print(df.info())
print(df["label"].value_counts())


   control_fail  red_fail  green_fail  vanishing_seen  total_correct  \
0             0         0           1               0             22   
1             4         6           4               2              4   
2             0         1           4               1             11   
3             0         1           1               0             22   
4             0         4           2               1             11   

   total_seen         label  
0          22        Normal  
1           8  RG_Deficient  
2          18  Deuteranopia  
3          22        Normal  
4          16    Protanopia  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   control_fail    10000 non-null  int64 
 1   red_fail        10000 non-null  int64 
 2   green_fail      10000 non-null  int64 
 3   vanishing_seen  10000 non-null  int64 
 4   total_corre

### Data Preprocessing Toolkit


In [ ]:
feature_columns = [
    "control_fail",
    "red_fail",
    "green_fail",
    "vanishing_seen",
    "total_correct",
    "total_seen"
]

X = df[feature_columns]
y = df["label"]

# encoding the catagorical data
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

joblib.dump(label_encoder, "label_encoder.pkl")

print(y_encoded)

# Train test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)


[1 3 0 ... 2 1 2]


### Model Training Toolkit


In [ ]:
rf_model = RandomForestClassifier(
    n_estimators=500,
    random_state=42
)

rf_model.fit(X_train, y_train)

# Model's prediction
y_pred = rf_model.predict(X_test)

### Model's Performance


In [ ]:
# estimating accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# confusion matrix 
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Accuracy: 1.0
Confusion Matrix:
 [[506   0   0   0]
 [  0 495   0   0]
 [  0   0 502   0]
 [  0   0   0 497]]


In [11]:
#saved trained model
joblib.dump(rf_model, "cvd_random_forest_model.pkl")


['cvd_random_forest_model.pkl']

In [12]:
# Prediction of the new user
sample_user = np.array([[4,6,0,2,10,12]])
y_pred = rf_model.predict(sample_user)

print(y_pred)

[2]


e:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
